name: CI (Dev)

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Navigate to Project Directory
        run: cd ${{ github.workspace }}/authenticationservice

      - name: List Contents of Project Directory
        run: ls -l ${{ github.workspace }}/authenticationservice
        
      - name: Navigate to Project Directory
        run: cd '/home/runner/work/AuthenticationService/AuthenticationService/authenticationservice/'

      - name: Build with Maven
        run: mvn -B clean package
        working-directory: ${{ github.workspace }}/authenticationservice

      - name: Run Tests
        run: mvn test
        working-directory: ${{ github.workspace }}/authenticationservice
